version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/workflow-templates"
      - "/.github/workflows"
    schedule:
      interval: "cron"
      cronjob: "0 2 * * *"
    groups:
      qubership-workflow-hub:
        patterns:
          - "netcracker/qubership-workflow-hub/*"
