name: Auto-Assign Project to Issue
run-name: Issue ${{ github.event.issue.number }} -> Project ${{ vars.PROJECT }}
on:
  issues:
    types: [opened, edited, reopened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to project
        id: add_project
        uses: actions/add-to-project@5afcf98fcd03f1c2f92c3c83f58ae24323cc57fd # v2.0.0
        with:
          project-url: https://github.com/orgs/Netcracker/projects/${{ vars.PROJECT }}?type=beta
          github-token: ${{ secrets.ADD_PROJECT_TO_ISSUE_PAT }}

      - name: Log info
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
        run: |
          echo "▶ Triggered by issue #${{ github.event.issue.number }}: $ISSUE_TITLE"
          echo "▶ Added to Project #${{ vars.PROJECT }} (beta)"
