name: Dev Mvn Docker Build
run-name: "Dev build repository: ${{ github.ref_name }} #${{ github.run_number }}"

on:
  workflow_dispatch:
    inputs:
      maven-command:
        description: 'Maven command'
        required: false
        type: string
        default: "--batch-mode package -Dgpg.skip=true"
      custom-image-name:
        description: 'Custom image name'
        required: false
        default: ''
      tags:
        description: 'Tags'
        required: false
        type: string
        default: ''
      java-version:
        description: 'Java version (e.g., 21)'
        required: false
        type: string
        default: "21"
      dry-run:
        description: 'Dry run'
        required: false
        type: boolean
        default: false
  push:
    branches:
    - '**'
    paths-ignore:
    - '.github/**'
    - 'docs/**'
    - 'CODE-OF-CONDUCT.md'
    - 'CONTRIBUTING.md'
    - 'LICENSE'
    - 'README.md'
    - 'SECURITY.md'
  pull_request:
    branches:
    - '**'
    paths-ignore:
    - '.github/**'
    - 'docs/**'
    - 'CODE-OF-CONDUCT.md'
    - 'CONTRIBUTING.md'
    - 'LICENSE'
    - 'README.md'
    - 'SECURITY.md'

permissions:
  contents: read

jobs:
  dev-build:
    name: "Maven Build and Docker Image Publish"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: "Checkout code"
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: "Maven build artifact"
        uses: netcracker/qubership-workflow-hub/actions/maven-snapshot-deploy@8d542a426ce561c7dce745f6b9cee068d1d7e101 #v2.0.10
        with:
          maven-command: "${{ github.event.inputs.maven-command || '--batch-mode clean install -Dgpg.skip=true' }}"
          java-version: ${{ github.event.inputs.java-version || '21' }}

      - name: "Generate metadata"
        uses: netcracker/qubership-workflow-hub/actions/metadata-action@main
        id: metadata

      - name: "Prepare tags"
        id: prepare_tags
        run: |
          BASE_TAG="${{ steps.metadata.outputs.result }}"
          EXTRA_TAG="${{ github.event.inputs.tags }}"
          if [ -n "$EXTRA_TAG" ]; then
            TAGS="${BASE_TAG}, ${EXTRA_TAG}"
          else
            TAGS="${BASE_TAG}"
          fi
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT

      - name: "Summary step"
        run: |
          echo "**Metadata:** ${{ steps.metadata.outputs.result }}" >> $GITHUB_STEP_SUMMARY
          echo "**Tags:** ${{ steps.prepare_tags.outputs.tags }}" >> $GITHUB_STEP_SUMMARY

      - name: "Build and Publish Docker Image"
        uses: netcracker/qubership-workflow-hub/actions/docker-action@8d542a426ce561c7dce745f6b9cee068d1d7e101 #v2.0.10
        with:
          custom-image-name: ${{ github.event.inputs.custom-image-name || '' }}
          platforms: ${{ env.PLATFORMS }}
          checkout: "false"
          tags: ${{ steps.prepare_tags.outputs.tags }}
          dry-run: ${{ github.event.inputs.dry-run || 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
