---

name: Maven release

on:
  workflow_dispatch:
    inputs:
      version-type:
        description: 'Version type to release'
        type: choice
        options:
          - 'major'
          - 'minor'
          - 'patch'
        required: true
        default: 'patch'
      profile:
        description: 'Maven profile to use'
        type: choice
        options:
          - ''
          - 'github'
          - 'central'
        required: true
        default: ''

permissions:
  contents: write
  packages: write

jobs:
  dry-run-build:
    runs-on: ubuntu-latest
    steps:
      - name: "Build and Publish"
        uses: netcracker/qubership-workflow-hub/actions/maven-release@main
        with:
          version-type: ${{ github.event.inputs.version-type }}
          module: ${{ github.repository }}
          maven-args: ''
          token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: 'true'
  deploy:
    needs: dry-run-build
    if: ${{ needs.dry-run-build.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: "Build and Publish"
        id: build-and-publish
        uses: netcracker/qubership-workflow-hub/actions/maven-release@main
        with:
          version-type: ${{ github.event.inputs.version-type }}
          module: ${{ github.repository }}
          maven-args: ""
          token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: 'false'
          server-id: ${{ inputs.profile }}
          profile: ${{ inputs.profile }}
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

  github-release:
    needs: deploy
    if: ${{ needs.deploy.result == 'success' }}
    uses: netcracker/qubership-workflow-hub/.github/workflows/release-drafter.yml@main
    with:
      version: ${{ github.event.client_payload.version }}
      publish: true
