name: NPM Publish

run-name: NPM Publish version ${{ inputs.version }}

on:
  workflow_dispatch:
    inputs:
      # =================================
      # GENERAL SETTINGS
      # =================================
      version:
        description: 'Version to publish (e.g., 1.0.0)'
        required: true
        type: string
      # =================================
      # NPM CONFIGURATION
      # =================================
      npm-scope:
        description: 'NPM scope for the package'
        required: false
        type: string
        default: '@netcracker'
      npm-dist-tag:
        description: 'NPM distribution tag'
        required: false
        type: string
        default: 'latest'
      update-nc-dependency:
        description: "Update NC dependencies"
        required: false
        type: boolean
        default: false
      registry-url:
        description: "NPM registry URL"
        required: false
        type: string
        default: "https://npm.pkg.github.com"
      node-version:
        description: "Node version"
        required: false
        type: string
        default: "22.x"
        
permissions:
  contents: write
  packages: write

jobs:
  npm-publish:
    uses: Netcracker/qubership-workflow-hub/.github/workflows/re-npm-publish.yml@v1.0.5
    with:
      version: ${{ inputs.version }}
      scope: ${{ inputs.npm-scope }}
      dist-tag: ${{ inputs.npm-dist-tag }}
      branch_name: ${{ github.ref_name }}
      update-nc-dependency: ${{ inputs.update-nc-dependency }}
      registry-url: ${{ inputs.registry-url }}
      node-version: ${{ inputs.node-version }}
    secrets: inherit
