name: PR Auto-Assignment
run-name: "Assigning reviewers for PR #${{ github.event.pull_request.number }}"
on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  pull-requests: write
  contents: read

jobs:
  pr-auto-assign:
    if: ${{ github.event.pull_request.base.repo.id == github.event.pull_request.head.repo.id }}
    uses: netcracker/qubership-workflow-hub/.github/workflows/re-pr-assigner.yml@main
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  warning-message:
    if: ${{ github.event.pull_request.base.repo.id != github.event.pull_request.head.repo.id }}
    runs-on: ubuntu-latest
    steps:
      - name: "Warning"
        run: |
          echo "⚠️ Pull request from fork! ⚠️" >> $GITHUB_STEP_SUMMARY
          echo "Assignees can not be set automatically. Set them manually please." >> $GITHUB_STEP_SUMMARY
