name: Assign PR
run-name: "Assigning reviewers for PR #${{ github.event.pull_request.number }}"
on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  pull-requests: write
  contents: read

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: PR Auto-Assignment
        uses: netcracker/qubership-workflow-hub/actions/pr-assigner@v1.0.3
        with:
          configuration-path: ".github/pr-assigner-config.yml"
          shuffle: 2
  warning-message:
    if: ${{ github.event.pull_request.base.repo.id != github.event.pull_request.head.repo.id }}
    runs-on: ubuntu-latest
    steps:
      - name: "Warning"
        run: |
          echo "⚠️ Pull request from fork! ⚠️" >> $GITHUB_STEP_SUMMARY
          echo "Assignees can not be set automatically. Set them manually please." >> $GITHUB_STEP_SUMMARY
