name: PR Auto-Assignment
run-name: "Assigning reviewers for PR #${{ github.event.pull_request.number }}"
on:
  pull_request_target:
    types: [opened, reopened, synchronize]
    branches:
    - main
permissions:
  pull-requests: write
  contents: read
jobs:
  pr-auto-assign:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
      with:
        persist-credentials: false

    - uses: netcracker/qubership-workflow-hub/actions/pr-assigner@4ce44398bac0a6f82e55aeb4a753aada3530de5b #v2.7.1
      with:
        assignees-count: 2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
